version: "3.8"

services:
  # Laravel Backend (PHP-FPM)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage/uploads:/var/www/html/storage/uploads
    networks:
      - local-network
    expose:
      - "9000"
    ports:
      - "9001:9000" # Expose backend on port 9001

  # Nginx Reverse Proxy (if needed later)
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html # Vue.js built files
    depends_on:
      - backend
      - frontend
    networks:
      - local-network

  # Frontend (Vue.js app)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
