version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/var/www/backend
    depends_on:
      - laravel
    networks:
      - local-network

  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel
    environment:
      - APP_URL=http://localhost
    volumes:
      - ./backend:/var/www/backend
    networks:
      - local-network
    ports:
      - "9000:9000"
    working_dir: /var/www/backend
    command: php artisan serve --host=0.0.0.0 --port=9000

  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ui
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
