version: "3.8"

services:
  # Laravel Backend (PHP-FPM)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage/uploads:/var/www/html/storage/uploads
    networks:
      - local-network
    expose:
      - "9000"

  # NGINX Reverse Proxy for both frontend and backend
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html # Serve Vue.js built files
      - ./backend:/var/www/html # Serve backend (Laravel)
    depends_on:
      - backend
      - frontend
    networks:
      - local-network

  # Vue.js Frontend (no web server needed)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    volumes:
      - ./frontend:/app
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
