version: "3.8"

services:
  # Backend (PHP-FPM for Laravel)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage/uploads:/var/www/html/storage/uploads
    networks:
      - local-network
    expose:
      - "9000"

  # NGINX Reverse Proxy for backend and frontend
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8000:80" # Exposing Nginx on port 8000
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Nginx config file
      - ./frontend/dist:/usr/share/nginx/html # Serving built Vue.js app
    depends_on:
      - backend
      - frontend
    networks:
      - local-network

  # Frontend (Vue.js app)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
