name: 📺 Backend - ⏱️ Verify

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Trigger the workflow on push to the main
  push:

  # Trigger the workflow on pull request
  pull_request:

jobs:
  qa-check:
    name: 🔦 Pipeline QA
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        php: [8.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Lint PHP
        run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

      - name: Run Pint
        run: ./vendor/bin/pint --test

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse

      - name: Run tests
        run: php artisan test
