name: Fix Code Style

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Trigger the workflow on push to the main
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        php: [8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint
        working-directory: ./backend
        run: composer global require laravel/pint

      - name: Run Pint
        working-directory: ./backend
        run: pint

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        # with:
        #   commit_message: "Fixes coding style"
